config/routes.rb
Rails.application.routes.draw do
  resources :checkout_sessions
  resources :products, only: %i[index create show destroy] do
    resources :prices, only: %i[create destroy]
  end
  resources :marinas
  resources :customer_yachts
  resources :yachts
  resources :customers
  resources :sessions, only: %i[create]
  resources :registrations, only: %i[create]
  delete :logout, to: 'sessions#logout'
  get :logged_in, to: 'sessions#logged_in'
  root to: 'static#home'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/yacht.rb
class Yacht < ApplicationRecord
  belongs_to :marina

  has_many :customer_yachts, dependent: :destroy
  has_many :customers, through: :customer_yachts
end

app/controllers/yachts_controller.rb
class YachtsController < ApplicationController
  before_action :set_yacht, only: [:show, :edit, :update, :destroy]
  include CurrentUserConcern

  # GET /yachts
  # GET /yachts.json
  def index
    @yachts = Yacht.all
  end

  # GET /yachts/1
  # GET /yachts/1.json
  def show
  end

  # GET /yachts/new
  def new
    @yacht = Yacht.new
  end

  # GET /yachts/1/edit
  def edit
  end

  # POST /yachts
  # POST /yachts.json
  def create
    @yacht = Yacht.new(yacht_params)

    respond_to do |format|
      if @yacht.save!
        CustomerYacht.find_or_create_by(yacht: @yacht, customer: @current_user)
        format.html { redirect_to @yacht, notice: 'Yacht was successfully created.' }
        format.json { render :show, status: :created, location: @yacht }
      else
        format.html { render :new }
        format.json { render json: @yacht.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /yachts/1
  # PATCH/PUT /yachts/1.json
  def update
    respond_to do |format|
      if @yacht.update!(yacht_params)
        format.html { redirect_to @yacht, notice: 'Yacht was successfully updated.' }
        format.json { render :show, status: :ok, location: @yacht }
      else
        format.html { render :edit }
        format.json { render json: @yacht.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /yachts/1
  # DELETE /yachts/1.json
  def destroy
    @yacht.destroy
    respond_to do |format|
      format.html { redirect_to yachts_url, status: 303 }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_yacht
      @yacht = Yacht.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def yacht_params
      params.require(:yacht).permit(:name, :length, :sail, :registration_number, :marina_id)
    end
end

app/helpers/yachts_helper.rb
module YachtsHelper
end

app/views/yachts/_form.html.erb
<%= form_with(model: yacht) do |form| %>
  <% if yacht.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(yacht.errors.count, "error") %> prohibited this yacht from being saved:</h2>

      <ul>
        <% yacht.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :length %>
    <%= form.number_field :length %>
  </div>

  <div class="field">
    <%= form.label :sail %>
    <%= form.check_box :sail %>
  </div>

  <div class="field">
    <%= form.label :registration_number %>
    <%= form.text_field :registration_number %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/yachts/edit.html.erb
<h1>Editing Yacht</h1>

<%= render 'form', yacht: @yacht %>

<%= link_to 'Show', @yacht %> |
<%= link_to 'Back', yachts_path %>

app/views/yachts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Yachts</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Length</th>
      <th>Sail</th>
      <th>Registration number</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @yachts.each do |yacht| %>
      <tr>
        <td><%= yacht.name %></td>
        <td><%= yacht.length %></td>
        <td><%= yacht.sail %></td>
        <td><%= yacht.registration_number %></td>
        <td><%= link_to 'Show', yacht %></td>
        <td><%= link_to 'Edit', edit_yacht_path(yacht) %></td>
        <td><%= link_to 'Destroy', yacht, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Yacht', new_yacht_path %>

app/views/yachts/new.html.erb
<h1>New Yacht</h1>

<%= render 'form', yacht: @yacht %>

<%= link_to 'Back', yachts_path %>

app/views/yachts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @yacht.name %>
</p>

<p>
  <strong>Length:</strong>
  <%= @yacht.length %>
</p>

<p>
  <strong>Sail:</strong>
  <%= @yacht.sail %>
</p>

<p>
  <strong>Registration number:</strong>
  <%= @yacht.registration_number %>
</p>

<%= link_to 'Edit', edit_yacht_path(@yacht) %> |
<%= link_to 'Back', yachts_path %>