config/routes.rb
Rails.application.routes.draw do
  resources :checkout_sessions
  resources :products, only: %i[index create show destroy] do
    resources :prices, only: %i[create destroy]
  end
  resources :marinas
  resources :customer_yachts
  resources :yachts
  resources :customers
  resources :sessions, only: %i[create]
  resources :registrations, only: %i[create]
  delete :logout, to: 'sessions#logout'
  get :logged_in, to: 'sessions#logged_in'
  root to: 'static#home'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/price.rb
class Price < ApplicationRecord
  belongs_to :product
  has_many :checkout_sessions
end

app/controllers/prices_controller.rb
class PricesController < ApplicationController
  before_action :get_product
  before_action :set_price, only: [:show, :edit, :update, :destroy]
  before_action :set_stripe_key
  include CurrentUserConcern


  # POST /prices
  # POST /prices.json
  def create
    if %w[day week month year].include?(price_params[:recurring_interval])
      @stripe_price = Stripe::Price.create(product: @product.stripe_product_id,
                                           unit_amount: price_params[:unit_amount].to_i,
                                           currency: 'usd',
                                           recurring: { 
                                            interval: price_params[:recurring_interval],
                                            interval_count: price_params[:recurring_count].to_i
                                                      })
    else
      @stripe_price = Stripe::Price.create(product: @product.stripe_product_id,
                                           unit_amount: price_params[:unit_amount].to_i,
                                           currency: 'usd')
    end

    @price = @product.prices.build(price_params)
    @price[:stripe_id] = @stripe_price['id']
    @price[:stripe_type] = @stripe_price['type']

    if @price.save!
      render json: @product, include: :prices
    else
      render json: {errors: 'there was an error'}
    end
  end

  # DELETE /prices/1
  # DELETE /prices/1.json
  def destroy
    @price.destroy
    respond_to do |format|
      format.html { redirect_to product_prices_path(@product), notice: 'Price was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def get_product
    @product = Product.find(params[:product_id])
  end

  def set_price
    @price = @product.prices.find(params[:id])
  end

  def set_stripe_key
    Stripe.api_key = 'sk_test_51I8VgBLQ8SRg06CGQYgJKACHjoPnXoN0pcNzoG3aCt4dXoDVJsMPL6HiYw0ISS8HGnx6hr3NGjbntXF5QTbFdqPW00idukCUXR'
  end

  # Only allow a list of trusted parameters through.
  def price_params
    params.require(:price).permit(:product_id, :unit_amount, :stripe_type, :recurring_interval, :recurring_count, :stripe_id)
  end
end

app/helpers/prices_helper.rb
module PricesHelper
end

app/views/prices/_form.html.erb
<%= form_with(model: [@product, price], local: true) do |form| %>
  <% if price.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(price.errors.count, "error") %> prohibited this price from being saved:</h2>

      <ul>
        <% price.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :product_id %>
    <%= form.text_field :product_id %>
  </div>

  <div class="field">
    <%= form.label :unit_amount %>
    <%= form.number_field :unit_amount %>
  </div>

  <div class="field">
    <%= form.label :stripe_type %>
    <%= form.text_field :stripe_type %>
  </div>

  <div class="field">
    <%= form.label :recurring_interval %>
    <%= form.text_field :recurring_interval %>
  </div>

  <div class="field">
    <%= form.label :recurring_count %>
    <%= form.number_field :recurring_count %>
  </div>

  <div class="field">
    <%= form.label :stripe_id %>
    <%= form.text_field :stripe_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/prices/edit.html.erb
<h1>Editing Price</h1>

<%= render 'form', price: @price %>

<%= link_to 'Show', product_price_path(@price) %> |
<%= link_to 'Back', product_prices_path %>

app/views/prices/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Prices</h1>

<table>
  <thead>
    <tr>
      <th>Product</th>
      <th>Unit amount</th>
      <th>Stripe Type</th>
      <th>Recurring interval</th>
      <th>Recurring count</th>
      <th>Stripe ID</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @prices.each do |price| %>
      <tr>
        <td><%= price.product_id %></td>
        <td><%= price.unit_amount %></td>
        <td><%= price.stripe_type %></td>
        <td><%= price.recurring_interval %></td>
        <td><%= price.recurring_count %></td>
        <td><%= price.stripe_id %></td>
        <td><%= link_to 'Show Product', [@product] %></td>
        <td><%= link_to 'Edit Price', edit_product_price_path(@product, price) %></td>
        <td><%= link_to 'Destroy', [@product, price], method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Price', new_product_price_path(@product) %>

app/views/prices/new.html.erb
<h1>New Price</h1>

<%= render 'form', price: @price %>

<%= link_to 'Back', product_prices_path(@product) %>

app/views/prices/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Product:</strong>
  <%= @price.product_id %>
</p>

<p>
  <strong>Unit amount:</strong>
  <%= @price.unit_amount %>
</p>

<p>
  <strong>Type:</strong>
  <%= @price.type %>
</p>

<p>
  <strong>Recurring interval:</strong>
  <%= @price.recurring_interval %>
</p>

<p>
  <strong>Recurring count:</strong>
  <%= @price.recurring_count %>
</p>

<p>
  <strong>Stripe:</strong>
  <%= @price.stripe_id %>
</p>

<%= link_to 'Edit', edit_price_path(@price) %> |
<%= link_to 'Back', prices_path %>