config/routes.rb
Rails.application.routes.draw do
  resources :checkout_sessions
  resources :products, only: %i[index create show destroy] do
    resources :prices, only: %i[create destroy]
  end
  resources :marinas
  resources :customer_yachts
  resources :yachts
  resources :customers
  resources :sessions, only: %i[create]
  resources :registrations, only: %i[create]
  delete :logout, to: 'sessions#logout'
  get :logged_in, to: 'sessions#logged_in'
  root to: 'static#home'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/customer_yacht.rb
class CustomerYacht < ApplicationRecord
  belongs_to :customer
  belongs_to :yacht
end

app/controllers/customer_yachts_controller.rb
class CustomerYachtsController < ApplicationController
  before_action :set_customer_yacht, only: [:show, :edit, :update, :destroy]

  # GET /customer_yachts
  # GET /customer_yachts.json
  def index
    @customer_yachts = CustomerYacht.all
  end

  # GET /customer_yachts/1
  # GET /customer_yachts/1.json
  def show
  end

  # GET /customer_yachts/new
  def new
    @customer_yacht = CustomerYacht.new
  end

  # GET /customer_yachts/1/edit
  def edit
  end

  # POST /customer_yachts
  # POST /customer_yachts.json
  def create
    @customer_yacht = CustomerYacht.new(customer_yacht_params)

    respond_to do |format|
      if @customer_yacht.save
        format.html { redirect_to @customer_yacht, notice: 'Customer yacht was successfully created.' }
        format.json { render :show, status: :created, location: @customer_yacht }
      else
        format.html { render :new }
        format.json { render json: @customer_yacht.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /customer_yachts/1
  # PATCH/PUT /customer_yachts/1.json
  def update
    respond_to do |format|
      if @customer_yacht.update(customer_yacht_params)
        format.html { redirect_to @customer_yacht, notice: 'Customer yacht was successfully updated.' }
        format.json { render :show, status: :ok, location: @customer_yacht }
      else
        format.html { render :edit }
        format.json { render json: @customer_yacht.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /customer_yachts/1
  # DELETE /customer_yachts/1.json
  def destroy
    @customer_yacht.destroy
    respond_to do |format|
      format.html { redirect_to customer_yachts_url, notice: 'Customer yacht was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_customer_yacht
      @customer_yacht = CustomerYacht.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def customer_yacht_params
      params.require(:customer_yacht).permit(:customer_id, :yacht_id)
    end
end

app/helpers/customer_yachts_helper.rb
module CustomerYachtsHelper
end

app/views/customer_yachts/_form.html.erb
<%= form_with(model: customer_yacht) do |form| %>
  <% if customer_yacht.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(customer_yacht.errors.count, "error") %> prohibited this customer_yacht from being saved:</h2>

      <ul>
        <% customer_yacht.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :customer_id %>
    <%= form.text_field :customer_id %>
  </div>

  <div class="field">
    <%= form.label :yacht_id %>
    <%= form.text_field :yacht_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/customer_yachts/edit.html.erb
<h1>Editing Customer Yacht</h1>

<%= render 'form', customer_yacht: @customer_yacht %>

<%= link_to 'Show', @customer_yacht %> |
<%= link_to 'Back', customer_yachts_path %>

app/views/customer_yachts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Customer Yachts</h1>

<table>
  <thead>
    <tr>
      <th>Customer</th>
      <th>Yacht</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @customer_yachts.each do |customer_yacht| %>
      <tr>
        <td><%= customer_yacht.customer_id %></td>
        <td><%= customer_yacht.yacht_id %></td>
        <td><%= link_to 'Show', customer_yacht %></td>
        <td><%= link_to 'Edit', edit_customer_yacht_path(customer_yacht) %></td>
        <td><%= link_to 'Destroy', customer_yacht, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Customer Yacht', new_customer_yacht_path %>

app/views/customer_yachts/new.html.erb
<h1>New Customer Yacht</h1>

<%= render 'form', customer_yacht: @customer_yacht %>

<%= link_to 'Back', customer_yachts_path %>

app/views/customer_yachts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Customer:</strong>
  <%= @customer_yacht.customer_id %>
</p>

<p>
  <strong>Yacht:</strong>
  <%= @customer_yacht.yacht_id %>
</p>

<%= link_to 'Edit', edit_customer_yacht_path(@customer_yacht) %> |
<%= link_to 'Back', customer_yachts_path %>