config/routes.rb
Rails.application.routes.draw do
  resources :checkout_sessions
  resources :products, only: %i[index create show destroy] do
    resources :prices, only: %i[create destroy]
  end
  resources :marinas
  resources :customer_yachts
  resources :yachts
  resources :customers
  resources :sessions, only: %i[create]
  resources :registrations, only: %i[create]
  delete :logout, to: 'sessions#logout'
  get :logged_in, to: 'sessions#logged_in'
  root to: 'static#home'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/product.rb
class Product < ApplicationRecord
  has_many :prices, dependent: :destroy
  belongs_to :user
  belongs_to :marina
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]
  before_action :set_stripe_key
  include CurrentUserConcern
  # GET /products
  # GET /products.json
  def index
    @products = Product.all
    render json: @products , include: :prices
  end

  def show
    render json: @product , include: :prices
  end
  # POST /products
  # POST /products.json
  def create
    @stripe_product = Stripe::Product.create(name: product_params[:name], description: product_params[:description])
    @product = Product.new(product_params)
    @product[:stripe_product_id] = @stripe_product['id']
    @product[:stripe_attributes] = @stripe_product['attributes']
    @product[:images] = @stripe_product['images']
    @product[:active] = true

    respond_to do |format|
      if @product.save!
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    Stripe::Product.delete(@product.stripe_product_id)
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: 'Product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_product
    @product = Product.find(params[:id])
  end
  def set_stripe_key
    Stripe.api_key = 'sk_test_51I8VgBLQ8SRg06CGQYgJKACHjoPnXoN0pcNzoG3aCt4dXoDVJsMPL6HiYw0ISS8HGnx6hr3NGjbntXF5QTbFdqPW00idukCUXR'
  end
  # Only allow a list of trusted parameters through.
  def product_params
    params.require(:product).permit(:user_id, :marina_id, :stripe_product_id, :active, :stripe_attributes, :description, :images, :name)
  end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/_form.html.erb
<%= form_with(model: product) do |form| %>
  <% if product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
        <% product.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :user_id %>
    <%= form.text_field :user_id %>
  </div>

  <div class="field">
    <%= form.label :marina_id %>
    <%= form.text_field :marina_id %>
  </div>

  <div class="field">
    <%= form.label :stripe_product_id %>
    <%= form.text_field :stripe_product_id %>
  </div>

  <div class="field">
    <%= form.label :active %>
    <%= form.check_box :active %>
  </div>

  <div class="field">
    <%= form.label :stripe_attributes %>
    <%= form.text_field :stripe_attributes %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description %>
  </div>

  <div class="field">
    <%= form.label :images %>
    <%= form.text_field :images %>
  </div>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/products/edit.html.erb
<h1>Editing Product</h1>

<%= render 'form', product: @product %>

<%= link_to 'Show', @product %> |
<%= link_to 'Back', products_path %>

app/views/products/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Products</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Marina</th>
      <th>Stripe product</th>
      <th>Active</th>
      <th>Stripe attributes</th>
      <th>Description</th>
      <th>Images</th>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @products.each do |product| %>
      <tr>
        <td><%= product.user_id %></td>
        <td><%= product.marina_id %></td>
        <td><%= product.stripe_product_id %></td>
        <td><%= product.active %></td>
        <td><%= product.stripe_attributes %></td>
        <td><%= product.description %></td>
        <td><%= product.images %></td>
        <td><%= product.name %></td>
        <td><%= link_to 'Show', product %></td>
        <td><%= link_to 'Edit', edit_product_path(product) %></td>
        <td><%= link_to 'Destroy', product, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Product', new_product_path %>

app/views/products/new.html.erb
<h1>New Product</h1>

<%= render 'form', product: @product %>

<%= link_to 'Back', products_path %>

app/views/products/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @product.user_id %>
</p>

<p>
  <strong>Marina:</strong>
  <%= @product.marina_id %>
</p>

<p>
  <strong>Stripe product:</strong>
  <%= @product.stripe_product_id %>
</p>

<p>
  <strong>Active:</strong>
  <%= @product.active %>
</p>

<p>
  <strong>Stripe attributes:</strong>
  <%= @product.stripe_attributes %>
</p>

<p>
  <strong>Description:</strong>
  <%= @product.description %>
</p>

<p>
  <strong>Images:</strong>
  <%= @product.images %>
</p>

<p>
  <strong>Name:</strong>
  <%= @product.name %>
</p>

<%= link_to 'Edit', edit_product_path(@product) %> |
<%= link_to 'Back', products_path %>